### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by ricardodesouza-br** [microsoft/Power-CAT-Copilot-Studio-Kit#64]
The tests that I created in the Kit are not running automatically. Futhermore, there are no runs in history of the "Run Copilot Tests" cloud flow.

I installed the latest solution version with the option to enable plug-ins steps enabled and I also verified that all cloud flows are enabled.  Do you have any tips about what may be causing this behaviour?

Regards

**Comment by psimolin** [comment]
Are you testing with end user authentication enabled? Are you getting any notifications when you save a new test run?

**Comment by mariofontana** [comment]
today I installed the solution and  I have the same issue. I'm testing without authentication and tests are not running and I don't see any error/warning.

**Comment by psimolin** [comment]
@mariofontana Were you able to confirm that the cloud flows are enabled?

**Comment by mariofontana** [comment]
Thank you @psimolin you pointed to the right direction,
The strange thing is that using the same account I used to install the solution and configure the first tests, it seems I don't have access to the cloud flows. If I try to turn them on, I receive an error 

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'xxx'. Connection 'cat_CopilotStudioAcceleratorDataverse' to 'shared_commondataserviceforapps' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for.

That's strange because I created that flow using the copilot studio kit app.

I'm definitely missing something because in the properties of the flow, I see my account as co-owner 
PS: I have the power automate P2 Viral. License

**Comment by patilravikiran** [comment]
@mariofontana, please share solution which you are using. We will try to reproduce this issue at our end.

**Comment by patilravikiran** [comment]
@mariofontana , gentle reminder to update.

**Comment by patilravikiran** [comment]
@mariofontana, gentle reminder to update.

**Comment by patilravikiran** [comment]
Closing this issue as no response from user. Thanks.
